<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add User - Step 1 — FlowDesk</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    fontFamily: { sans: ['Inter', 'sans-serif'] }
                }
            }
        }
    </script>
</head>
<body class="bg-gray-50 min-h-screen flex items-center justify-center font-sans p-4">
    <div class="bg-white rounded-2xl shadow-sm border border-gray-200 w-full max-w-lg p-8">
        <div class="flex items-center gap-3 mb-6">
            <div class="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center">
                <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z"/>
                </svg>
            </div>
            <div>
                <h1 class="text-xl font-bold text-gray-900">Add New User</h1>
                <p class="text-sm text-gray-500">Step 1 of 3 — Company Info</p>
            </div>
        </div>

        <form method="POST" action="<?= base_url('user/add_step1') ?>" enctype="multipart/form-data">
            <div class="space-y-4">
                <div>
                    <label for="profile_picture" class="block text-sm font-medium text-gray-700 mb-1">User Image</label>
                    <input type="file" id="profile_picture" name="profile_picture" accept="image/*" required
                           class="w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100">
                </div>

                <div>
                    <label for="role" class="block text-sm font-medium text-gray-700 mb-1">Role</label>
                    <select name="role" id="role" required
                            class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent">
                        <option value="" disabled selected>Select Role</option>
                        <option value="admin">Admin</option>
                        <option value="mechanic">Mechanic</option>
                        <option value="receptionist">Receptionist</option>
                    </select>
                </div>

                <div>
                    <label for="company_id" class="block text-sm font-medium text-gray-700 mb-1">Company ID</label>
                    <input type="text" id="company_id" name="company_id" readonly
                           class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm bg-gray-50 text-gray-500 focus:outline-none">
                    <p class="text-xs text-gray-400 mt-1">Autogenerated ID</p>
                </div>

                <div>
                    <label for="date_of_employment" class="block text-sm font-medium text-gray-700 mb-1">Date of Employment</label>
                    <input type="text" id="date_of_employment" name="date_of_employment" readonly value="<?= date('Y-m-d') ?>"
                           class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm bg-gray-50 text-gray-500 focus:outline-none">
                </div>
            </div>

            <div class="flex justify-end mt-6">
                <button type="button" id="nextStep"
                        class="bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg px-5 py-2.5 text-sm font-medium transition-colors">
                    Next Step
                </button>
            </div>
        </form>
    </div>

    <script>
        document.getElementById('role').addEventListener('change', function() {
            const role = this.value;
            const year = new Date().getFullYear().toString().slice(-2);
            const rolePrefixes = { admin: 'ADM', mechanic: 'MECH', receptionist: 'RP' };

            fetch("<?= base_url('user/getLastId') ?>?role=" + role)
                .then(response => response.json())
                .then(data => {
                    const lastId = parseInt(data.result) + 1;
                    const formattedId = String(lastId).padStart(3, '0');
                    document.getElementById('company_id').value = `${rolePrefixes[role]}${year}${formattedId}`;
                    document.getElementById('date_of_employment').value = new Date().toISOString().split('T')[0];
                })
                .catch(error => console.error('Error:', error));
        });

        document.getElementById('nextStep').addEventListener('click', function() {
            const form = document.querySelector('form');
            const formData = new FormData(form);
            formData.append('<?= csrf_token() ?>', '<?= csrf_hash() ?>');

            fetch("<?= base_url('user/add_step1') ?>", {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    window.location.href = "<?= base_url('user/add_step2') ?>";
                } else {
                    alert(data.message);
                }
            })
            .catch(error => console.error('Error:', error));
        });
    </script>
</body>
</html>
